# Generated by Django 5.1.7 on 2025-03-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimeSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("checkin_time", models.TimeField(blank=True, null=True)),
                ("checkout_time", models.TimeField(blank=True, null=True)),
                ("break_time", models.TimeField(blank=True, null=True)),
                ("total_hours", models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
