# Generated by Django 5.1.7 on 2025-03-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_attendance_delete_timesheet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("day", models.CharField(max_length=10)),
                ("in_time", models.TimeField(blank=True, null=True)),
                ("out_time", models.TimeField(blank=True, null=True)),
                ("duration", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
    ]
