# Generated by Django 5.1.7 on 2025-04-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_timeentrys_delete_timeentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentrys",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
