# Generated by Django 5.1.7 on 2025-04-26 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_timeentrys_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("IN", "Clock In"), ("OUT", "Clock Out")],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TimeSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("day", models.CharField(max_length=10)),
                (
                    "total_duration",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TimeEntrys",
        ),
        migrations.AddField(
            model_name="timeentry",
            name="timesheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="core.timesheet",
            ),
        ),
    ]
